blog/urls.py
# coding: utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',  views.index, name='index'),
    url(r'^artcle', views.ArticleView.as_view(), name='article'),
    url(r'^author', views.AuthorView.as_view(), name='author'),
    url(r'^tag', views.TagView.as_view(), name='tag'),
    url(r'^(?P<article_id>[0-9]+)/$', views.detail, name='detail'),
]

#url()中第一项是域名的匹配，尖括号中是views带来的信息， 第二项是与调用view参数，第三项是name，其他模板通过命名来引用URL
#让主URLconf可以链接到polls.urls模块。在mysite/urls.py中插入一个include()：

learn/urls.py
# coding: utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',  views.index, name='home'),
    url(r'^add/(\d+)/(\d+)/$', views.old_add2_redirect),
    url(r'^new_add/(\d+)/(\d+)/', views.add2, name='add2'),
]
#url()中第一项是域名的匹配，尖括号中是views带来的信息， 第二项是与调用view参数，第三项是name，其他模板通过命名来引用URL
#让主URLconf可以链接到polls.urls模块。在mysite/urls.py中插入一个include()：

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^learn/', include('learn.urls', namespace="learn")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
]

polls/urls.py
# coding: utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',  views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]
#url()中第一项是域名的匹配，尖括号中是views带来的信息， 第二项是与调用view参数，第三项是name，其他模板通过命名来引用URL
#让主URLconf可以链接到polls.urls模块。在mysite/urls.py中插入一个include()：

blog/models.py
#coding=utf-8
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models


@python_2_unicode_compatible
class Author(models.Model):
    name = models.CharField(max_length=50)
    qq = models.CharField(max_length=10)
    addr = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Article(models.Model):
    title = models.CharField(max_length=50)
    author = models.ForeignKey(Author)
    content = models.TextField()
    score = models.IntegerField()  # 文章的打分
    tags = models.ManyToManyField('Tag')
    #img = models.

    def __str__(self):
        return self.title


@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

learn/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

polls/models.py
#coding=utf-8
from django.db import models
import datetime
from django.utils import timezone
# polls应用的模型
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
    #给你的模型添加__str__()方法会使你自己在使用交互式命令行时看得更加方便，而且会在Django自动生成的管理界面中使用对象的这种表示。
        return self.question_text
    def was_published_recently(self):
    #添加一个自定义方法
        return self.pub_date >=timezone.now()-datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True#绿色的打钩样式
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
'''
每个模型都用一个类表示，该类继承自django.db.models.Model。每个模型都有一些类变量，在模型中每个类变量都代表了数据库中的一个字段。

每个字段通过Field类的一个实例表示 —— 例如字符字段CharField和日期字段DateTimeField。这种方法告诉Django，每个字段中保存着什么类型的数据。

每个Field 实例的名字（例如question_text 或 pub_date）就是字段的名字，并且是机器可读的格式。你将在Python代码中使用到它的值，并且你的数据库将把它用作表的列名。

我们使用ForeignKey定义了一个关联。它告诉Django每个Choice都只关联一个Question。Django支持所有常见的数据库关联：多对一、多对多和一对一。
'''

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Tag, Author
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse

# Create your views here.

def index(request):

    return render(request, 'blog/index1.html', {
        'article': "article",
        'author': "author",
        'tag':'tag',
    })
class AuthorView(generic.ListView):

    template_name = 'blog/author.html'
    context_object_name = 'author_list'

    def get_queryset(self):
        return Author.objects.order_by('name')[:5]

class TagView(generic.ListView):

    template_name = 'blog/tag.html'
    context_object_name = 'tag_list'

    def get_queryset(self):
        return Tag.objects.order_by('name')[:5]

class ArticleView(generic.ListView):

    template_name = 'blog/HomePage.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        return Article.objects.order_by('title')[:5]


def detail(request, article_id):
    p = get_object_or_404(Article, pk=article_id)
    img_list = ['1.jpg','2.jpg','3.jpg','4.jpg','5.jpg']
    return render(request, 'blog/detail.html', {
            'article': p,
            'article_list': Article.objects.order_by('title')[:5],
            'img_list':img_list,
            'img':'1.jpg'

        })

learn/views.py
#coding:utf-8
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse

def index(request):
    context = {'context':'whoooops'}
    return render(request, 'learn/home.html',context)
#context 是字典，字典第一项在HTML中为调用参数

def add(request):
    a = request.GET['a']
    b = request.GET['b']
    c =int(a) + int(b)
    return HttpResponse(str(c))

def add2(request,a,b):
    d = int(a) + int(b)
    return HttpResponse(str(d))

def old_add2_redirect(request,a ,b):
    return HttpResponseRedirect(
        reverse('learn:add2', args=(int(a),int(b)))
    )

blog/templates/blog/HomePage.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<meta charset="utf-8">
<title>文章发布网站</title>
<link rel="stylesheet" type="text/css" href="{% static 'blog/HomePage.css' %}"/>
</head>

<body>
<header>
  <a href="{% url 'blog:article' %}"><img src="{%static 'blog/images/logo.png' %}" alt="logo"/></a>
  <h3>欢迎来到XXX网站</h3>
  <div id="reg">
    <span><a href="#">登录</a></span>
    <a href="#">注册</a>
  </div>
</header>
<div id="main">
  <nav>
    <ul>
      <li><a href="#">网站首页</a></li>
      <li><a href="#">关于我们</a></li>
      <li><a href="#">联系我们</a></li>
      <li><a href="#">意见反馈</a></li>
    </ul>
  </nav>
  {% if article_list %}
  <section>
    <div id="FocusImg">
      <img src="{%static 'blog/images/焦点图.png' %}" alt="焦点图">
    </div>
    {% for article in article_list %}
  <div class="responsive">
    <a href="{% url 'blog:detail' article.id %}">
    <div class="img">
        <img src="{% static 'blog/images/'%}{{forloop.counter}}.jpg" alt="1" width="300" height="200"/>
      <div class="desc">
        <p class="title">{{ article.title}}</p>
        <p class="brief">{{ article.author}}</p>
      </div>
    </div>
      {% endfor %}
    </a>
  </div>
  </section>
  {% endif %}
</div>
<!--
<footer>
  footer
</footer>
-->
</body>
</html>

blog/templates/blog/article.html
{% load staticfiles %}

{% if article_list %}
    <ul>
    {% for article in article_list %}
        <li><a href="{% url 'blog:detail' article.id %}">{{ article.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}这是学习{% endblock %} 好好学习，天天向上！⊙ω⊙</title>
</head>
<body>


{% block content %}
<div>我要好好学习 []~(￣▽￣)~*　</div>
{% endblock %}


</body>
</html

blog/templates/blog/detail.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<meta charset="utf-8">
<title>文章正文</title>
<link rel="stylesheet" type="text/css" href="{% static 'blog/article.css' %}"/>
</head>

<body>
<header>
  <a href="{% url 'blog:article' %}"><img src="{%static 'blog/images/logo.png' %}" alt="logo"/></a>
  <a href="HomePage.html"><h2>XXX网站</h2></a>
  <div id=nav>
    <ul>
      <li><a href="#"  id="news">正文</a></li>
      <li><a href="#">关于我们</a></li>
      <li><a href="#">联系我们</a></li>
    </ul>
  </div>
</header>
<div id="main">
  <article>
  <div class="title">
      <h2>{{ article.title}}</h2>
    </div>
    <div class="author">
      <img src="{%static 'blog/images/author.png' %}" alt="author"/>
      <p>{{ article.author}}</p>
    </div>
    <hr/>
    <div class="content">
      {{ article.content}}
    </div>
  </article>
  <aside>
    <p>相关推荐</p>
    {% if article_list %}
    <ul>
      {% for article in article_list %}
      <li><a href="{% url 'blog:detail' article.id %}">{{ article.title }}</a></li>
      {% endfor %}
    </ul>
  {% endif %}
  </aside>
</div>
<footer>
  <p>©&nbsp;这里是版权信息</p>
</footer>
</body>
</html>

blog/templates/blog/home.html
<!DOCTYPE html>


<html>
<head>
{% if request.user.is_authenticated %}
    {{ request.user.username }}，您好！
{% else %}
    请登陆，这里放登陆链接
    {{ request.path }}
    {{ request.GET.urlencode }}
{% endif %}

</body>
</html>

blog/templates/blog/index.html
{% load staticfiles %}

{% if high_score_blog_list %}
    <ul>
    {% for blog in high_score_blog_list %}
        <li><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

blog/templates/blog/index1.html
{% load staticfiles %}

    <ul>
        <li><a href="{% url 'blog:article' %}">{{ article }}</a></li>
        <li><a href="{% url 'blog:tag' %}">{{ tag }}</a></li>
        <li><a href="{% url 'blog:author' %}">{{ author}}</a></li>
    </ul>

blog/templates/blog/results.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />


<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>